# Setup
title: Vanessa Kwong
description: I am a fifth-year physics undergraduate at University of California, Riverside.
url: https://veecarling.github.io
avatar: /profilephoto.jpg
paginate: 5
permalink: pretty
cover_image: /bg.jpg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
twitter:
  username: v
  card: summary
logo: logo.png
social:
  name: Vanessa Kwong
  links:
    - https://twitter.com/veecarling
    - https://github.com/veecarling
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: Vanessa Kwong
  url: https://github.com/veecarling/
  email: skwon056@ucr.edu
